# Generated by Django 5.1.3 on 2024-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("user", "user")], max_length=255
            ),
        ),
    ]
